### ISSUE TITLE
Make this as RAM fast dictionary.

### ISSUE THREAD

**Issue by RamanjaneyuluIdavalapati** [deep-compute/diskdict#6]
- The python dictionary is very fast in getting values for given keys
- Make sure the diskdict also as fast as python dictionary.

**Comment by jaswanth098** [comment]
not working on this actively moving this to ready

**Comment by juncaofish** [comment]
any update for this? or are there any read performance comparison with native dict in python?

**Comment by sundarrajan78** [comment]
@jaswanth098 Is there any action required?
